remove common utilities
* remove the bash utils carried forward from the old mysql part
* do not run slurmrestd in "all" mode

diff --git a/src/slurm-wrappers/wrappers/slurmrestd b/src/slurm-wrappers/wrappers/slurmrestd
--- a/src/slurm-wrappers/wrappers/slurmrestd
+++ b/src/slurm-wrappers/wrappers/slurmrestd
@@ -5,30 +5,20 @@ set -e
 
 # Check to see if we should even start
 snap_mode=$(cat $SNAP_COMMON/snap_mode)
-if ! [[ $snap_mode == "slurmrestd" || $snap_mode = "all" ]]; then
+if ! [[ $snap_mode == "slurmrestd" ]]; then
         exit 0
 fi
 
-. "$SNAP/utilities/common-utilities"
+
 export SLURM_CONF=$SNAP_COMMON/etc/slurm/slurm.conf
-export SLURMCTLD_INIT=$SNAP_COMMON/etc/slurm-snap-init-utils/slurmctld-init-complete
 
-# Wait for slurmctld if snap.mode="all"
-if [[ $snap_mode = "all" ]]; then
-
-    while ! [[ -f $SLURMCTLD_INIT ]]
-    do
-        pprint "Waiting for SLURMCTLD to initialize";
-	sleep 1
-    done
-fi
 
 # Start slurmrestd only if we have a config file
 if ! [[ -f $SLURM_CONF ]]; then
-    pprint "No slurm conf, cannot start process.";
+    printf "No slurm conf, cannot start process.";
     exit -1
 fi
 
-pprint "Starting SLURMRESTD";
+printf "Starting SLURMRESTD";
 exec "$SNAP/sbin/slurmrestd" \
     "-f" "$SLURM_CONF" `hostname -s`:6820 "$@" 
